name: Node.js Package (legacy)

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

env:
  GPR_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Register additional private repositories
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${GPR_AUTH_TOKEN}" >> .npmrc
          echo "@inway:registry=https://npm.pkg.github.com" >> .npmrc
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Publish to GPR
        run: yarn publish --tag legacy
        continue-on-error: true
      - name: Switch publishing to npmjs.org
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" >> .npmrc
          echo "@inway:registry=https://registry.npmjs.org" >> .npmrc
      - name: Publish to npmjs.org
        run: yarn publish --tag legacy
